In [140]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_excel(r"C:\Users\ANCHAL\Desktop\CODING\ML\LUNG CANCER DATASET.xlsx")
dataset

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
0,M,65,1,1,1,2,2,1,2,2,2,2,2,2,1,NO
1,F,55,1,2,2,1,1,2,2,2,1,1,1,2,2,NO
2,F,78,2,2,1,1,1,2,1,2,1,1,2,1,1,YES
3,M,60,2,1,1,1,2,1,2,1,1,2,1,2,2,YES
4,F,80,1,1,2,1,1,2,1,2,1,1,1,1,2,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,F,71,2,1,1,2,2,1,1,1,1,2,1,1,2,NO
2996,F,75,1,2,1,1,1,2,2,2,2,1,1,2,1,NO
2997,F,62,2,2,2,1,2,2,2,2,1,1,2,2,2,YES
2998,M,30,1,1,2,2,2,2,2,2,2,1,2,1,2,YES
2999,M,40,1,2,2,1,1,1,2,2,2,1,1,1,1,YES

In [141]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split

In [142]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 1/3, random_state = 0)

In [143]:
print (X_train, y_train)

[['M' 79 2 ... 2 1 1]
 ['M' 44 2 ... 1 1 1]
 ['M' 73 1 ... 1 2 2]
 ...
 ['F' 33 1 ... 2 1 1]
 ['M' 56 1 ... 1 1 1]
 ['F' 69 2 ... 2 1 2]] ['NO' 'YES' 'NO' ... 'NO' 'YES' 'NO']

In [108]:
from sklearn.linear_model import LinearRegression

In [109]:
regressor = LinearRegression()

In [144]:
print (X_test, y_test)

[['F' 78 2 ... 1 2 1]
 ['M' 48 2 ... 1 1 1]
 ['M' 51 2 ... 1 2 1]
 ...
 ['M' 44 1 ... 2 1 2]
 ['M' 53 1 ... 1 1 1]
 ['M' 77 2 ... 2 1 1]] ['YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO'
 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO'
 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES'
 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO'
 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES'
 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO'
 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO'
 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO'
 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO'
 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO'
 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES'
 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES'
 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO'
 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES'
 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO'
 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES'
 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES'
 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES'
 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES'
 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES'
 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO'
 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES'
 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES'
 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES' 'YES'
 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES'
 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO'
 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO'
 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES'
 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES'
 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO'
 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES'
 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO'
 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO'
 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO'
 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES'
 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES'
 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO'
 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES'
 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES'
 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO'
 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES'
 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO'
 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES'
 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO'
 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO'
 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO'
 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES'
 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO'
 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO'
 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES'
 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES'
 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO'
 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO'
 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES'
 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO'
 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO'
 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO'
 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO'
 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES'
 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO'
 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES'
 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO'
 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO'
 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES'
 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES'
 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO'
 'YES' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES'
 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES'
 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO'
 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO'
 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO'
 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES'
 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES'
 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO'
 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO'
 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES'
 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES']

In [145]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the 'Gender' column
dataset['GENDER'] = dataset['GENDER'].replace({'M': 1, 'F': 0})

In [146]:
dataset['LUNG_CANCER'] = dataset['LUNG_CANCER'].replace({'NO': 0, 'YES': 1})

In [147]:
print(dataset)

      GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0          1   65        1               1        1              2
1          0   55        1               2        2              1
2          0   78        2               2        1              1
3          1   60        2               1        1              1
4          0   80        1               1        2              1
...      ...  ...      ...             ...      ...            ...
2995       0   71        2               1        1              2
2996       0   75        1               2        1              1
2997       0   62        2               2        2              1
2998       1   30        1               1        2              2
2999       1   40        1               2        2              1

      CHRONIC_DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL_CONSUMING  \
0                   2        1        2         2                  2
1                   1        2        2         2                  1
2                   1        2        1         2                  1
3                   2        1        2         1                  1
4                   1        2        1         2                  1
...               ...      ...      ...       ...                ...
2995                2        1        1         1                  1
2996                1        2        2         2                  2
2997                2        2        2         2                  1
2998                2        2        2         2                  2
2999                1        1        2         2                  2

      COUGHING  SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN  \
0            2                    2                      2           1
1            1                    1                      2           2
2            1                    2                      1           1
3            2                    1                      2           2
4            1                    1                      1           2
...        ...                  ...                    ...         ...
2995         2                    1                      1           2
2996         1                    1                      2           1
2997         1                    2                      2           2
2998         1                    2                      1           2
2999         1                    1                      1           1

      LUNG_CANCER
0               0
1               0
2               1
3               1
4               0
...           ...
2995            0
2996            0
2997            1
2998            1
2999            1

[3000 rows x 16 columns]

In [148]:
#dataset = dataset[~dataset['LUNG_CANCER_encoded'].isin(['0', '1'])]

In [149]:
#dataset = dataset[~dataset['GENDER_encoded'].isin(['0', '1'])]

In [150]:
print(dataset)

      GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0          1   65        1               1        1              2
1          0   55        1               2        2              1
2          0   78        2               2        1              1
3          1   60        2               1        1              1
4          0   80        1               1        2              1
...      ...  ...      ...             ...      ...            ...
2995       0   71        2               1        1              2
2996       0   75        1               2        1              1
2997       0   62        2               2        2              1
2998       1   30        1               1        2              2
2999       1   40        1               2        2              1

      CHRONIC_DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL_CONSUMING  \
0                   2        1        2         2                  2
1                   1        2        2         2                  1
2                   1        2        1         2                  1
3                   2        1        2         1                  1
4                   1        2        1         2                  1
...               ...      ...      ...       ...                ...
2995                2        1        1         1                  1
2996                1        2        2         2                  2
2997                2        2        2         2                  1
2998                2        2        2         2                  2
2999                1        1        2         2                  2

      COUGHING  SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN  \
0            2                    2                      2           1
1            1                    1                      2           2
2            1                    2                      1           1
3            2                    1                      2           2
4            1                    1                      1           2
...        ...                  ...                    ...         ...
2995         2                    1                      1           2
2996         1                    1                      2           1
2997         1                    2                      2           2
2998         1                    2                      1           2
2999         1                    1                      1           1

      LUNG_CANCER
0               0
1               0
2               1
3               1
4               0
...           ...
2995            0
2996            0
2997            1
2998            1
2999            1

[3000 rows x 16 columns]

In [151]:
unique_genders = dataset['GENDER'].unique()
print(unique_genders)
dataset['GENDER'] = dataset['GENDER'].replace('Unknown', pd.NA)
print(dataset)
valid_genders = ['F', 'M']

def clean_gender(GENDER):
    if GENDER not in valid_GENDER:
        return pd.NA  # Replace invalid entry with NaN
    return GENDER

dataset['GENDER'] = dataset['GENDER'].apply(clean_gender)
print(dataset)
dataset_cleaned = dataset.dropna(subset=['GENDER'])
print(dataset_cleaned)

[1 0]
      GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0          1   65        1               1        1              2
1          0   55        1               2        2              1
2          0   78        2               2        1              1
3          1   60        2               1        1              1
4          0   80        1               1        2              1
...      ...  ...      ...             ...      ...            ...
2995       0   71        2               1        1              2
2996       0   75        1               2        1              1
2997       0   62        2               2        2              1
2998       1   30        1               1        2              2
2999       1   40        1               2        2              1

      CHRONIC_DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL_CONSUMING  \
0                   2        1        2         2                  2
1                   1        2        2         2                  1
2                   1        2        1         2                  1
3                   2        1        2         1                  1
4                   1        2        1         2                  1
...               ...      ...      ...       ...                ...
2995                2        1        1         1                  1
2996                1        2        2         2                  2
2997                2        2        2         2                  1
2998                2        2        2         2                  2
2999                1        1        2         2                  2

      COUGHING  SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN  \
0            2                    2                      2           1
1            1                    1                      2           2
2            1                    2                      1           1
3            2                    1                      2           2
4            1                    1                      1           2
...        ...                  ...                    ...         ...
2995         2                    1                      1           2
2996         1                    1                      2           1
2997         1                    2                      2           2
2998         1                    2                      1           2
2999         1                    1                      1           1

      LUNG_CANCER
0               0
1               0
2               1
3               1
4               0
...           ...
2995            0
2996            0
2997            1
2998            1
2999            1

[3000 rows x 16 columns]

NameError: name 'valid_GENDER' is not defined

In [152]:
try:
    dataset['GENDER'] = dataset['GENDER'].astype(float)
    dataset['AGE'] = dataset['AGE'].astype(float)
    dataset['LUNG_CANCER'] = dataset['LUNG_CANCER'].astype(float)
except ValueError as e:
    print(f"ValueError: {e}")
    # Handle the error or clean the data
    # For example, replace 'M' with NaN (Not a Number)
    dataset['GENDER'] = pd.to_numeric(dataset['GENDER'], errors='coerce')
    dataset['AGE'] = pd.to_numeric(dataset['AGE'], errors='coerce')
    dataset['LUNG_CANCER'] = pd.to_numeric(dataset['LUNG_CANCER'], errors='coerce')
print(dataset)

      GENDER   AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0        1.0  65.0        1               1        1              2
1        0.0  55.0        1               2        2              1
2        0.0  78.0        2               2        1              1
3        1.0  60.0        2               1        1              1
4        0.0  80.0        1               1        2              1
...      ...   ...      ...             ...      ...            ...
2995     0.0  71.0        2               1        1              2
2996     0.0  75.0        1               2        1              1
2997     0.0  62.0        2               2        2              1
2998     1.0  30.0        1               1        2              2
2999     1.0  40.0        1               2        2              1

      CHRONIC_DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL_CONSUMING  \
0                   2        1        2         2                  2
1                   1        2        2         2                  1
2                   1        2        1         2                  1
3                   2        1        2         1                  1
4                   1        2        1         2                  1
...               ...      ...      ...       ...                ...
2995                2        1        1         1                  1
2996                1        2        2         2                  2
2997                2        2        2         2                  1
2998                2        2        2         2                  2
2999                1        1        2         2                  2

      COUGHING  SHORTNESS_OF_BREATH  SWALLOWING_DIFFICULTY  CHEST_PAIN  \
0            2                    2                      2           1
1            1                    1                      2           2
2            1                    2                      1           1
3            2                    1                      2           2
4            1                    1                      1           2
...        ...                  ...                    ...         ...
2995         2                    1                      1           2
2996         1                    1                      2           1
2997         1                    2                      2           2
2998         1                    2                      1           2
2999         1                    1                      1           1

      LUNG_CANCER
0             0.0
1             0.0
2             1.0
3             1.0
4             0.0
...           ...
2995          0.0
2996          0.0
2997          1.0
2998          1.0
2999          1.0

[3000 rows x 16 columns]

In [153]:
regressor.fit(X_train, Y_train)

ValueError: could not convert string to float: 'M'